apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.ocomc.labels.nodemgr.name }}-external
    namespace: {{ .Release.Namespace }}
spec:
    selector:
        application: {{ .Values.ocomc.labels.nodemgr.name }}
    ports:
    -   name: ocomc-nodemgr-port
        nodePort: {{ .Values.ocomc.configEnv.nmExternalPort | default 31001 }}
        port: {{ .Values.ocomc.configEnv.nmExternalPort | default 31001 }}
        targetPort: {{ .Values.ocomc.configEnv.nmExternalPort | default 31001 }}
        protocol: TCP
    type: NodePort
    externalTrafficPolicy: Cluster
