apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.ocomc.labels.adminserver.name }}-external
    namespace: {{ .Release.Namespace }}
spec:
    selector:
        application: {{ .Values.ocomc.labels.adminserver.name }}
    ports:
    -   name: ocomc-adminserver-port
        nodePort: {{ .Values.ocomc.configEnv.adminsvrExternalPort | default 31000 }}
        port: {{ .Values.ocomc.configEnv.adminsvrExternalPort | default 31000 }}
        targetPort: {{ .Values.ocomc.configEnv.adminsvrExternalPort | default 31000 }}
        protocol: TCP
    -   name: ocomc-adminserver-firewall-port
        nodePort: {{ .Values.ocomc.configEnv.adminsvrFirewallPort | default 31002 }}
        port: {{ .Values.ocomc.configEnv.adminsvrFirewallPort | default 31002 }}
        targetPort: {{ .Values.ocomc.configEnv.adminsvrFirewallPort | default 31002 }}
        protocol: TCP
    type: NodePort
    externalTrafficPolicy: Cluster
